### ISSUE TITLE
Implement Slack Notification on CI/CD Build Failure

### ISSUE THREAD

**Issue by rblessings** [rblessings/terraform#50]
As part of improving our CI/CD pipeline visibility and ensuring timely response to build failures, I propose adding a Slack notification integration to our GitHub Actions workflow. This will allow us to be promptly notified when any build fails, particularly useful for quick troubleshooting and resolution.

# Proposal

Implement a new job in the GitHub Actions workflow that will notify a Slack channel whenever a build fails. The notification should include key details about the failure, such as the repository name and a direct link to the failed run, allowing team members to take immediate action.

Here is the code snippet for the job:

```yaml

## Notify Slack on failure
notify-slack:
  if: failure()  # This job will run only if any of the above jobs fail
  runs-on: ubuntu-latest
  steps:
    - name: Send Slack Notification
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"*Pipeline Failure* - Terraform Validation failed for the repository ${GITHUB_REPOSITORY}.
            \n\nDetails: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\"
        }" ${{ secrets.SLACK_WEBHOOK_URL }}

```

## Key Points:

- **Trigger:** The notification should be triggered only when a failure occurs in the CI/CD pipeline (`if: failure()`).
- **Details:** Include the repository name and a link to the specific failed run for easy debugging.
- **Webhook URL:** The Slack webhook URL should be stored securely in the repository secrets (`SLACK_WEBHOOK_URL`).
- **Scope:** Initially, this will be implemented for Terraform validation, but the same pattern can be extended to other workflows as needed.

## Benefits:

- **Improved Visibility:** Teams will be notified in real-time whenever a failure occurs, reducing the time spent identifying issues.
- **Faster Response:** With Slack integration, the team can act on build failures immediately, without having to manually check the CI/CD status.
- **Proactive Monitoring:** Helps in proactively monitoring the CI/CD pipeline health, especially for critical jobs like Terraform validation.

## Next Steps:

1. Review the proposed change.
2. Ensure that the Slack webhook URL is securely stored in the repository secrets.
3. Implement the Slack notification job in the workflow.

Let me know if there are any questions or additional details needed for this proposal.
